services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    image: payload-next-prod
    restart: always
    env_file:
      - .env.production
    depends_on:
      - postgres
    ports:
      - '3000:3000' # later remove when nginx is added
    networks:
      - app-network

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: elegardens
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
