services:
  payload:
    build: .
    image: elegardens:latest
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - media_data:/app/media

  postgres:
    restart: always
    image: postgres:17.6
    environment:
      - POSTGRES_USER=payload
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=elegardens
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata_prod:
  media_data:
