import configPromise from '@payload-config'
import { getPayload } from 'payload'
import { NextResponse } from 'next/server'
import { getAuthenticatedClient } from '@/lib/auth-client'

export async function POST(request: Request) {
  try {
    // Check authentication
    const client = await getAuthenticatedClient()
    if (!client) {
      return NextResponse.json(
        {
          success: false,
          error: 'Unauthorized',
        },
        { status: 401 }
      )
    }

    const body = await request.json()
    const { deliveryDate, items, notes } = body

    // Validate required fields
    if (!deliveryDate || !items || items.length === 0) {
      return NextResponse.json(
        {
          success: false,
          error: 'Delivery date and at least one item are required',
        },
        { status: 400 }
      )
    }

    // Get Payload instance
    const payload = await getPayload({
      config: configPromise,
    })

    // Create order
    // Note: orderNumber is auto-generated by beforeChange hook in Orders collection
    const order = await payload.create({
      collection: 'orders',
      data: {
        client: client.id,
        companyName: client.companyName,
        deliveryDate,
        items: items.map((item: any) => ({
          product: item.product,
          quantity: item.quantity,
        })),
        notes: notes || undefined,
        status: 'pending',
      } as any, // Type assertion needed because orderNumber is auto-generated
    })

    return NextResponse.json(
      {
        success: true,
        order: {
          id: order.id,
          orderNumber: order.orderNumber,
        },
      },
      { status: 201 }
    )
  } catch (error: any) {
    console.error('Order creation error:', error)
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Failed to create order',
      },
      { status: 500 }
    )
  }
}
