/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    clients: ClientAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    pots: Pot;
    employees: Employee;
    projects: Project;
    blogs: Blog;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    clients: Client;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pots: PotsSelect<false> | PotsSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'announcement-banner': AnnouncementBanner;
    about: About;
    'privacy-policy': PrivacyPolicy;
  };
  globalsSelect: {
    'announcement-banner': AnnouncementBannerSelect<false> | AnnouncementBannerSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Client & {
        collection: 'clients';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  productId: string;
  /**
   * rose-bushy (lowercase, hyphens only, no spaces or special characters)
   */
  slug: string;
  common_name: string;
  availability: 'available' | 'out-of-stock';
  quantity?: number | null;
  description_en: string;
  description_de: string;
  height: string;
  diameter: string;
  hardiness: string;
  light_en: 'full-sun' | 'partial-sun' | 'partial-shade' | 'full-shade';
  light_de: 'full-sun' | 'partial-sun' | 'partial-shade' | 'full-shade';
  /**
   * Upload up to 6 product photos.
   */
  images?: (number | Media)[] | null;
  /**
   * Choose a card background color
   */
  color?: string | null;
  /**
   * 50-60 characters
   */
  metaTitle_en?: string | null;
  /**
   * 50-60 characters
   */
  metaTitle_de?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_en?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_de?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pots".
 */
export interface Pot {
  id: number;
  potId: string;
  /**
   * Enter any name for the pot (e.g., sm, md, lg, xl, Small, Medium, etc.)
   */
  name: string;
  /**
   * Enter dimensions in the format: 10cm x 10cm
   */
  size?: string | null;
  availability: 'available' | 'out-of-stock';
  quantity?: number | null;
  /**
   * Upload a pot image
   */
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  first_name: string;
  last_name: string;
  email?: string | null;
  telephone?: string | null;
  role_en: string;
  role_de: string;
  department_en?: string | null;
  department_de?: string | null;
  profilePicture?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * bahnhof-path (lowercase, hyphens only, no spaces or special characters)
   */
  slug: string;
  position?: number | null;
  client: string;
  title_en: string;
  title_de: string;
  tagline_en?: string | null;
  tagline_de?: string | null;
  category_en: string;
  category_de: string;
  image?: (number | null) | Media;
  sections?:
    | (
        | {
            subtitle_en?: string | null;
            subtitle_de?: string | null;
            paragraphs: {
              text_en: string;
              text_de: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            caption_en?: string | null;
            caption_de?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
      )[]
    | null;
  /**
   * 50-60 characters
   */
  metaTitle_en?: string | null;
  /**
   * 50-60 characters
   */
  metaTitle_de?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_en?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_de?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * blog-post-title (lowercase, hyphens only, no spaces or special characters)
   */
  slug: string;
  position?: number | null;
  title_en: string;
  title_de: string;
  summary_en?: string | null;
  summary_de?: string | null;
  author?: string | null;
  publishedDate?: string | null;
  coverImage?: (number | null) | Media;
  sections?:
    | (
        | {
            subtitle_en?: string | null;
            subtitle_de?: string | null;
            paragraphs: {
              text_en: string;
              text_de: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-block';
          }
        | {
            image: number | Media;
            caption_en?: string | null;
            caption_de?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-block';
          }
      )[]
    | null;
  /**
   * 50-60 characters
   */
  metaTitle_en?: string | null;
  /**
   * 50-60 characters
   */
  metaTitle_de?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_en?: string | null;
  /**
   * 150-160 characters
   */
  metaDescription_de?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstname: string;
  lastname: string;
  /**
   * Contact email address
   */
  email: string;
  /**
   * Optional phone number
   */
  phone?: string | null;
  /**
   * Message from the contact form
   */
  message: string;
  /**
   * Status of the contact submission
   */
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  /**
   * Internal notes about this submission
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  /**
   * Subscriber email address
   */
  email: string;
  /**
   * User has given consent to receive newsletters
   */
  consent?: boolean | null;
  /**
   * Subscription status
   */
  status?: ('active' | 'unsubscribed' | 'bounced') | null;
  /**
   * Date and time of subscription
   */
  subscribedAt?: string | null;
  /**
   * Date and time of unsubscription (if applicable)
   */
  unsubscribedAt?: string | null;
  /**
   * Internal notes about this subscriber
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientId: string;
  companyName: string;
  contactPerson?: string | null;
  phone?: string | null;
  address: string;
  status: 'active' | 'inactive';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Contact email address (also used for password reset)
   */
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  client: number | Client;
  companyName: string;
  orderDate?: string | null;
  /**
   * Requested delivery date (client input)
   */
  deliveryDate: string;
  items: {
    itemId: string;
    itemName: string;
    quantity: number;
    id?: string | null;
  }[];
  /**
   * Current order status
   */
  status: 'pending' | 'confirmed' | 'processing' | 'completed' | 'cancelled';
  /**
   * Notes from client with order
   */
  notes?: string | null;
  /**
   * Internal admin notes
   */
  adminNotes?: string | null;
  /**
   * Language used when order was created
   */
  locale?: ('en' | 'de') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pots';
        value: number | Pot;
      } | null)
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productId?: T;
  slug?: T;
  common_name?: T;
  availability?: T;
  quantity?: T;
  description_en?: T;
  description_de?: T;
  height?: T;
  diameter?: T;
  hardiness?: T;
  light_en?: T;
  light_de?: T;
  images?: T;
  color?: T;
  metaTitle_en?: T;
  metaTitle_de?: T;
  metaDescription_en?: T;
  metaDescription_de?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pots_select".
 */
export interface PotsSelect<T extends boolean = true> {
  potId?: T;
  name?: T;
  size?: T;
  availability?: T;
  quantity?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  first_name?: T;
  last_name?: T;
  email?: T;
  telephone?: T;
  role_en?: T;
  role_de?: T;
  department_en?: T;
  department_de?: T;
  profilePicture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  position?: T;
  client?: T;
  title_en?: T;
  title_de?: T;
  tagline_en?: T;
  tagline_de?: T;
  category_en?: T;
  category_de?: T;
  image?: T;
  sections?:
    | T
    | {
        'text-block'?:
          | T
          | {
              subtitle_en?: T;
              subtitle_de?: T;
              paragraphs?:
                | T
                | {
                    text_en?: T;
                    text_de?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-block'?:
          | T
          | {
              image?: T;
              caption_en?: T;
              caption_de?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle_en?: T;
  metaTitle_de?: T;
  metaDescription_en?: T;
  metaDescription_de?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T;
  position?: T;
  title_en?: T;
  title_de?: T;
  summary_en?: T;
  summary_de?: T;
  author?: T;
  publishedDate?: T;
  coverImage?: T;
  sections?:
    | T
    | {
        'text-block'?:
          | T
          | {
              subtitle_en?: T;
              subtitle_de?: T;
              paragraphs?:
                | T
                | {
                    text_en?: T;
                    text_de?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-block'?:
          | T
          | {
              image?: T;
              caption_en?: T;
              caption_de?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle_en?: T;
  metaTitle_de?: T;
  metaDescription_en?: T;
  metaDescription_de?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstname?: T;
  lastname?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  consent?: T;
  status?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientId?: T;
  companyName?: T;
  contactPerson?: T;
  phone?: T;
  address?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  client?: T;
  companyName?: T;
  orderDate?: T;
  deliveryDate?: T;
  items?:
    | T
    | {
        itemId?: T;
        itemName?: T;
        quantity?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  adminNotes?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-banner".
 */
export interface AnnouncementBanner {
  id: number;
  enabled?: boolean | null;
  /**
   * Add multiple announcements. Each announcement has both English and German text side by side.
   */
  announcements?:
    | {
        text_en?: string | null;
        text_de?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Background color of the banner (hex format, e.g., #0b7a43)
   */
  backgroundColor?: string | null;
  /**
   * Text color of the banner (hex format, e.g., #ffffff)
   */
  textColor?: string | null;
  /**
   * Semi Bold: Subtle emphasis. Bold: Recommended for most announcements. Extra Bold: Maximum visibility for urgent messages.
   */
  fontWeight?: ('semibold' | 'bold' | 'extrabold') | null;
  /**
   * Display banner on desktop devices (md breakpoint and above)
   */
  showOnDesktop?: boolean | null;
  /**
   * Display banner on mobile devices (below md breakpoint)
   */
  showOnMobile?: boolean | null;
  /**
   * Speed of the scrolling animation
   */
  speed?: ('slow' | 'medium' | 'fast') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  roots_title_en: string;
  roots_title_de: string;
  roots_intro_en: string;
  roots_intro_de: string;
  roots_signature_en?: string | null;
  roots_signature_de?: string | null;
  milestones_title_en?: string | null;
  milestones_title_de?: string | null;
  milestones?:
    | {
        title_en: string;
        title_de: string;
        subtitle1_en?: string | null;
        subtitle1_de?: string | null;
        desc1_en?: string | null;
        desc1_de?: string | null;
        subtitle2_en?: string | null;
        subtitle2_de?: string | null;
        desc2_en?: string | null;
        desc2_de?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  our_story_title_en?: string | null;
  our_story_title_de?: string | null;
  ceo_title_en?: string | null;
  ceo_title_de?: string | null;
  ceo_desc_en?: string | null;
  ceo_desc_de?: string | null;
  ceo_image?: (number | null) | Media;
  mission_title_en?: string | null;
  mission_title_de?: string | null;
  mission_desc_en?: string | null;
  mission_desc_de?: string | null;
  vision_title_en?: string | null;
  vision_title_de?: string | null;
  vision_desc_en?: string | null;
  vision_desc_de?: string | null;
  values_title_en?: string | null;
  values_title_de?: string | null;
  values_desc_en?: string | null;
  values_desc_de?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  sections?:
    | {
        title_en: string;
        title_de: string;
        content_en: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        content_de: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-banner_select".
 */
export interface AnnouncementBannerSelect<T extends boolean = true> {
  enabled?: T;
  announcements?:
    | T
    | {
        text_en?: T;
        text_de?: T;
        id?: T;
      };
  backgroundColor?: T;
  textColor?: T;
  fontWeight?: T;
  showOnDesktop?: T;
  showOnMobile?: T;
  speed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  roots_title_en?: T;
  roots_title_de?: T;
  roots_intro_en?: T;
  roots_intro_de?: T;
  roots_signature_en?: T;
  roots_signature_de?: T;
  milestones_title_en?: T;
  milestones_title_de?: T;
  milestones?:
    | T
    | {
        title_en?: T;
        title_de?: T;
        subtitle1_en?: T;
        subtitle1_de?: T;
        desc1_en?: T;
        desc1_de?: T;
        subtitle2_en?: T;
        subtitle2_de?: T;
        desc2_en?: T;
        desc2_de?: T;
        image?: T;
        id?: T;
      };
  our_story_title_en?: T;
  our_story_title_de?: T;
  ceo_title_en?: T;
  ceo_title_de?: T;
  ceo_desc_en?: T;
  ceo_desc_de?: T;
  ceo_image?: T;
  mission_title_en?: T;
  mission_title_de?: T;
  mission_desc_en?: T;
  mission_desc_de?: T;
  vision_title_en?: T;
  vision_title_de?: T;
  vision_desc_en?: T;
  vision_desc_de?: T;
  values_title_en?: T;
  values_title_de?: T;
  values_desc_en?: T;
  values_desc_de?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title_en?: T;
        title_de?: T;
        content_en?: T;
        content_de?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}